version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    allow:
      - dependency-type: "direct"
    open-pull-requests-limit: 100
    versioning-strategy: "increase"
    rebase-strategy: "disabled"
    groups:
      dev-dependencies:
        patterns:
          - "@stylistic/eslint-plugin-js"
          - "@symfony/webpack-encore"
          - "eslint"
          - "sass"
          - "sass-loader"
          - "webpack"
          - "webpack-cli"
      tabler:
        patterns:
          - "@tabler/*"

  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "monthly"
    allow:
      - dependency-type: "direct"
    open-pull-requests-limit: 100
    versioning-strategy: "increase"
    rebase-strategy: "disabled"
    groups:
      dev-dependencies:
        dependency-type: "development"
      symfony:
        dependency-type: "production"
        patterns:
          - "symfony/*"
      twig:
        dependency-type: "production"
        patterns:
          - "twig/*"
