version: "3.5"

services:
  telemetry.glpi-project.org:
    container_name: "telemetry.glpi-project.org"
    build:
      context: ".docker/development"
    volumes:
      - ".:/var/www/telemetry.glpi-project.org:rw"
    extra_hosts:
      - "host.docker.internal:host-gateway"
