name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        php-version: [8.1]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install

    - name: Use PHP ${{ matrix.php-version }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        extensions: mbstring, pdo_mysql
    - uses: php-actions/composer@v6

    - name: Install Symfony CLI
      uses: symfony/cli-action@v1

    - name: Initialize database
      run: symfony console doctrine:database:create --env=test
      run: symfony console doctrine:migrations:migrate --env=test --no-interaction
      env:
        APP_ENV: test

    - name: build application
      run: npm run build

    - name: Start web server
      run: symfony serve &
      env:
        APP_ENV: test

    - run: vendor/bin/phpunit