name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: test
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    strategy:
      matrix:
        node-version: [16.x]
        php-version: [8.1]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install

    - name: Use PHP ${{ matrix.php-version }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        extensions: mbstring, pdo_mysql
    - uses: php-actions/composer@v6

    - name: Initialize database
      run: |
        php bin/console doctrine:database:drop --if-exists --force --env=test
        php bin/console doctrine:database:create --env=test &&
        php bin/console doctrine:migrations:migrate --env=test --no-interaction
      env:
        APP_ENV: test
        DATABASE_URL: mysql://root:password@db:3306/test

    - name: Build application
      run: npm run build

    - name: Start web server
      run: symfony serve &
      env:
        APP_ENV: test
        DATABASE_URL: mysql://root:password@localhost:3306/test

    - run: vendor/bin/phpunit